# Generated by Django 4.1.7 on 2023-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(max_length=100)),
                ('areaName', models.CharField(max_length=1000)),
                ('areaType', models.CharField(max_length=50)),
            ],
        ),
    ]
