# Generated by Django 4.1.7 on 2023-05-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0002_areas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
