# Generated by Django 4.1.7 on 2023-05-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
