# Generated by Django 4.1.7 on 2023-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covid19App', '0004_delete_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(max_length=100)),
                ('areaName', models.CharField(max_length=1000)),
                ('areaType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='MetricDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('deprecated', models.CharField(max_length=100)),
                ('doc_last_modified', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=100)),
                ('metric_name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MetricDetails',
            },
        ),
    ]
